### ISSUE TITLE
small question

### ISSUE THREAD

**Issue by firmianay** [0xdea/semgrep-rules#5]
Hi, what does the double brackets (( used here mean, I have not found a similar usage description?

```
    pattern-either:
      # type-based patterns (some types are missing)
      - patterns:
        - pattern: sizeof((char * $PTR))
        - pattern-not: sizeof("...")
      - pattern: sizeof((int * $PTR))
      - pattern: sizeof((float * $PTR))
      - pattern: sizeof((double * $PTR))
```
