### ISSUE TITLE
Exclude css from raptor bad words

### ISSUE THREAD

**Issue by meme-lord** [0xdea/semgrep-rules#7]
Not sure if this is a change you'd like but words like "overflow" and warning" appear commonly in css files but are never anything to investigate closer and can probably be excluded
```yml
    paths:
       exclude:
          - "*.css" 
          - "*.scss" 
```
